package com.company;
/**
 * class SalesRepr which contains the seller properties.
 * created 23rd of May 2018 as homework2 for Scoala Informala de IT
 *
 * @author Ioana
 *
 */
public class SalesRepr {
    public String sellerName;
    public int noOfSales;
    public double quotaPerSale;

    public SalesRepr(String sellerName, int noOfSales, double quotaPerSale) {
        this.sellerName = sellerName;
        this.noOfSales = noOfSales;
        this.quotaPerSale = quotaPerSale;
    }

    //this method calculates the revenue generated by each Sales Representative
    public double getRevenue() {
        return noOfSales * quotaPerSale;
    }

}
